export const ListOfBrackets = {
    noHero: {
        2: [
            {
                bracket: "2x20",
                minAverage: 0,
                maxAverage: 20.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x30",
                minAverage: 21,
                maxAverage: 30.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x39",
                minAverage: 31,
                maxAverage: 39.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x42",
                minAverage: 40,
                maxAverage: 42.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x47",
                minAverage: 43,
                maxAverage: 47.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x54",
                minAverage: 48,
                maxAverage: 54.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x55",
                minAverage: 55,
                maxAverage: 55.9,
                status: "Deprecated!",
                exceptions: "",
                type: "soup",
            },
        ],
        3: [{
            bracket: "3x20",
            minAverage: 0,
            maxAverage: 20.9,
            status: "Active!",
            exceptions: "",
            type: "",
        },
            {
                bracket: "3x30",
                minAverage: 21,
                maxAverage: 30.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x39",
                minAverage: 31,
                maxAverage: 39.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x42",
                minAverage: 40,
                maxAverage: 42.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x47",
                minAverage: 43,
                maxAverage: 47.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x54",
                minAverage: 48,
                maxAverage: 54.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x55",
                minAverage: 55,
                maxAverage: 55.9,
                status: "Deprecated!",
                exceptions: "",
                type: "soup",
            },
        ],
        4: [
            {
                bracket: "4x20",
                minAverage: 0,
                maxAverage: 20.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x30",
                minAverage: 21,
                maxAverage: 30.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x39",
                minAverage: 31,
                maxAverage: 39.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x42",
                minAverage: 40,
                maxAverage: 42.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x47",
                minAverage: 43,
                maxAverage: 47.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x54",
                minAverage: 48,
                maxAverage: 54.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x55",
                minAverage: 55,
                maxAverage: 55.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "4x62",
                minAverage: 56,
                maxAverage: 62.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x69",
                minAverage: 63,
                maxAverage: 69.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x70",
                minAverage: 70,
                maxAverage: 70.9,
                status: "Deprecated!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "4x77",
                minAverage: 71,
                maxAverage: 77.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ],
        5: [
            {
                bracket: "5x20",
                minAverage: 0,
                maxAverage: 20.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x30",
                minAverage: 21,
                maxAverage: 30.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x39",
                minAverage: 31,
                maxAverage: 39.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x42",
                minAverage: 40,
                maxAverage: 42.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x47",
                minAverage: 43,
                maxAverage: 47.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x54",
                minAverage: 48,
                maxAverage: 54.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x55",
                minAverage: 55,
                maxAverage: 55.9,
                status: "Active!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "5x62",
                minAverage: 56,
                maxAverage: 62.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x69",
                minAverage: 63,
                maxAverage: 69.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x70",
                minAverage: 70,
                maxAverage: 70.9,
                status: "Active!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "5x77",
                minAverage: 71,
                maxAverage: 77.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x84",
                minAverage: 78,
                maxAverage: 84.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ]
    },
    withHero: {
        5: [
            {
                bracket: "5x54",
                minAverage: 48,
                maxAverage: 54.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x55",
                minAverage: 55,
                maxAverage: 55.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "5x62",
                minAverage: 56,
                maxAverage: 62.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x69",
                minAverage: 63,
                maxAverage: 69.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x70",
                minAverage: 70,
                maxAverage: 70.9,
                status: "Active!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "5x77",
                minAverage: 71,
                maxAverage: 77.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x84",
                minAverage: 78,
                maxAverage: 84.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x85",
                minAverage: 85,
                maxAverage: 85.9,
                status: "Active!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "5x94",
                minAverage: 86,
                maxAverage: 94.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ],
        6: [
            {
                bracket: "6x54",
                minAverage: 48,
                maxAverage: 54.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x55",
                minAverage: 55,
                maxAverage: 55.9,
                status: "Deprecated!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "6x62",
                minAverage: 56,
                maxAverage: 62.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x69",
                minAverage: 63,
                maxAverage: 69.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x70",
                minAverage: 70,
                maxAverage: 70.9,
                status: "Active!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "6x77",
                minAverage: 71,
                maxAverage: 77.9,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x84",
                minAverage: 78,
                maxAverage: 84.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x85",
                minAverage: 85,
                maxAverage: 85.9,
                status: "Active!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "6x94",
                minAverage: 86,
                maxAverage: 94.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
        ],
        7: [

            {
                bracket: "7x84",
                minAverage: 78,
                maxAverage: 84.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "7x85",
                minAverage: 85,
                maxAverage: 85.9,
                status: "Deprecated!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "7x94",
                minAverage: 86,
                maxAverage: 94.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "7x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
        ],
        8: [
            {
                bracket: "8x84",
                minAverage: 78,
                maxAverage: 84.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "8x85",
                minAverage: 85,
                maxAverage: 85.9,
                status: "Deprecated!",
                exceptions: "",
                type: "soup",
            },
            {
                bracket: "8x94",
                minAverage: 86,
                maxAverage: 94.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "8x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
        ]
    }
}