export const ListOfBrackets = [
    {
        noHero: [
            {
                barracks: 2,
                brackets: [
                    {
                        bracket: "2x20",
                        minAvarage: 0.1,
                        maxAverage: 20,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "2x30",
                        minAvarage: 20.1,
                        maxAverage: 30,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "2x39",
                        minAvarage: 30.1,
                        maxAverage: 39,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "2x42",
                        minAvarage: 39.1,
                        maxAverage: 42,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "2x47",
                        minAvarage: 42.1,
                        maxAverage: 47,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "2x54",
                        minAvarage: 47.1,
                        maxAverage: 54,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "2x55",
                        minAvarage: 54.1,
                        maxAverage: 55,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                ]
            },
            {
                barracks: 3,
                brackets: [
                    {
                        bracket: "3x20",
                        minAvarage: 0.1,
                        maxAverage: 20,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "3x30",
                        minAvarage: 20.1,
                        maxAverage: 30,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "3x39",
                        minAvarage: 30.1,
                        maxAverage: 39,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "3x42",
                        minAvarage: 39.1,
                        maxAverage: 42,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "3x47",
                        minAvarage: 42.1,
                        maxAverage: 47,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "3x54",
                        minAvarage: 47.1,
                        maxAverage: 54,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "3x55",
                        minAvarage: 54.1,
                        maxAverage: 55,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                ]
            },
            {
                barracks: 4,
                brackets: [
                    {
                        bracket: "4x20",
                        minAvarage: 0.1,
                        maxAverage: 20,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x30",
                        minAvarage: 20.1,
                        maxAverage: 30,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x39",
                        minAvarage: 30.1,
                        maxAverage: 39,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x42",
                        minAvarage: 39.1,
                        maxAverage: 42,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x47",
                        minAvarage: 42.1,
                        maxAverage: 47,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x54",
                        minAvarage: 47.1,
                        maxAverage: 54,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x55",
                        minAvarage: 54.1,
                        maxAverage: 55,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x62",
                        minAvarage: 55.1,
                        maxAverage: 62,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x69",
                        minAvarage: 62.1,
                        maxAverage: 69,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x70",
                        minAvarage: 69.1,
                        maxAverage: 70,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "4x77",
                        minAvarage: 70.1,
                        maxAverage: 77,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                ]
            },
            {
                barracks: 5,
                brackets: [
                    {
                        bracket: "5x20",
                        minAvarage: 0.1,
                        maxAverage: 20,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x30",
                        minAvarage: 20.1,
                        maxAverage: 30,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x39",
                        minAvarage: 30.1,
                        maxAverage: 39,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x42",
                        minAvarage: 39.1,
                        maxAverage: 42,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x47",
                        minAvarage: 42.1,
                        maxAverage: 47,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x54",
                        minAvarage: 47.1,
                        maxAverage: 54,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x55",
                        minAvarage: 54.1,
                        maxAverage: 55,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x62",
                        minAvarage: 55.1,
                        maxAverage: 62,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x69",
                        minAvarage: 62.1,
                        maxAverage: 69,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x70",
                        minAvarage: 69.1,
                        maxAverage: 70,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x77",
                        minAvarage: 70.1,
                        maxAverage: 77,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x84",
                        minAvarage: 77.1,
                        maxAverage: 84,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                ]
            },
        ],
        withHero: [
            {
                barracks: 5,
                brackets: [
                    {
                        bracket: "5x54",
                        minAvarage: 47.1,
                        maxAverage: 54,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x55",
                        minAvarage: 54.1,
                        maxAverage: 55,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x62",
                        minAvarage: 55.1,
                        maxAverage: 62,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x69",
                        minAvarage: 62.1,
                        maxAverage: 69,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x70",
                        minAvarage: 69.1,
                        maxAverage: 70,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x77",
                        minAvarage: 70.1,
                        maxAverage: 77,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x84",
                        minAvarage: 77.1,
                        maxAverage: 84,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x85",
                        minAvarage: 84.1,
                        maxAverage: 85,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x94",
                        minAvarage: 85.1,
                        maxAverage: 94,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "5x100",
                        minAvarage: 94.1,
                        maxAverage: 100,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                ]
            },
            {
                barracks: 6,
                brackets: [
                    {
                        bracket: "6x54",
                        minAvarage: 47.1,
                        maxAverage: 54,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x55",
                        minAvarage: 54.1,
                        maxAverage: 55,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x62",
                        minAvarage: 55.1,
                        maxAverage: 62,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x69",
                        minAvarage: 62.1,
                        maxAverage: 69,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x70",
                        minAvarage: 69.1,
                        maxAverage: 70,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x77",
                        minAvarage: 70.1,
                        maxAverage: 77,
                        status: "Not Recommened!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x84",
                        minAvarage: 77.1,
                        maxAverage: 84,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x85",
                        minAvarage: 84.1,
                        maxAverage: 85,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x94",
                        minAvarage: 85.1,
                        maxAverage: 94,
                        status: "Active!",
                        exceptions: "",
                    },
                    {
                        bracket: "6x100",
                        minAvarage: 94.1,
                        maxAverage: 100,
                        status: "Active!",
                        exceptions: "",
                    },
                ]
            },
            {
                barracks: 7,
                brackets: [

                    {
                        bracket: "7x84",
                        minAvarage: 77.1,
                        maxAverage: 84,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "7x85",
                        minAvarage: 84.1,
                        maxAverage: 85,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "7x94",
                        minAvarage: 85.1,
                        maxAverage: 94,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "7x100",
                        minAvarage: 94.1,
                        maxAverage: 100,
                        status: "Active!",
                        exceptions: "",
                    },
                ]
            },
            {
                barracks: 8,
                brackets: [
                    {
                        bracket: "8x84",
                        minAvarage: 77.1,
                        maxAverage: 84,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "8x85",
                        minAvarage: 84.1,
                        maxAverage: 85,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "8x94",
                        minAvarage: 85.1,
                        maxAverage: 94,
                        status: "Deprecated!",
                        exceptions: "",
                    },
                    {
                        bracket: "8x100",
                        minAvarage: 94.1,
                        maxAverage: 100,
                        status: "Active!",
                        exceptions: "",
                    },
                ]
            },
        ],

    }
]