export const soupExceptions = {
    noHero: {
        2: [
            {
                bracket: "2x20",
                minAverage: 0,
                maxAverage: 20,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x30",
                minAverage: 21,
                maxAverage: 30,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x39",
                minAverage: 31,
                maxAverage: 40,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x47",
                minAverage: 41,
                maxAverage: 47,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "2x54",
                minAverage: 48,
                maxAverage: 55,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ],
        3: [{
            bracket: "3x20",
            minAverage: 0,
            maxAverage: 20,
            status: "Active!",
            exceptions: "",
            type: "",
        },
            {
                bracket: "3x30",
                minAverage: 21,
                maxAverage: 30,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x39",
                minAverage: 31,
                maxAverage: 40,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x47",
                minAverage: 41,
                maxAverage: 47,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "3x54",
                minAverage: 48,
                maxAverage: 55,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ],
        4: [
            {
                bracket: "4x20",
                minAverage: 0,
                maxAverage: 20,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x30",
                minAverage: 21,
                maxAverage: 30,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x39",
                minAverage: 31,
                maxAverage: 40,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x47",
                minAverage: 41,
                maxAverage: 47,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x54",
                minAverage: 48,
                maxAverage: 55,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x62",
                minAverage: 56,
                maxAverage: 62,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x69",
                minAverage: 63,
                maxAverage: 70,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "4x77",
                minAverage: 71,
                maxAverage: 77,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ],
        5: [
            {
                bracket: "5x20",
                minAverage: 0,
                maxAverage: 20,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x30",
                minAverage: 21,
                maxAverage: 30,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x39",
                minAverage: 31,
                maxAverage: 40,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x47",
                minAverage: 41,
                maxAverage: 47,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x54",
                minAverage: 48,
                maxAverage: 55,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x62",
                minAverage: 56,
                maxAverage: 62,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x69",
                minAverage: 63,
                maxAverage: 70,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x77",
                minAverage: 71,
                maxAverage: 77,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x84",
                minAverage: 78,
                maxAverage: 85,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ]
    },
    withHero: {
        5: [
            {
                bracket: "5x54",
                minAverage: 48,
                maxAverage: 55,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x62",
                minAverage: 56,
                maxAverage: 62,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x69",
                minAverage: 63,
                maxAverage: 70,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x77",
                minAverage: 71,
                maxAverage: 77,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x84",
                minAverage: 78,
                maxAverage: 85,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x94",
                minAverage: 86,
                maxAverage: 94,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "5x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
        ],
        6: [
            {
                bracket: "6x54",
                minAverage: 48,
                maxAverage: 55,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x62",
                minAverage: 56,
                maxAverage: 62,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x69",
                minAverage: 63,
                maxAverage: 70,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x77",
                minAverage: 71,
                maxAverage: 77,
                status: "Not Recommended!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x84",
                minAverage: 78,
                maxAverage: 85,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x94",
                minAverage: 86,
                maxAverage: 94,
                status: "Active!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "6x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
        ],
        7: [

            {
                bracket: "7x84",
                minAverage: 78,
                maxAverage: 85,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "7x94",
                minAverage: 86,
                maxAverage: 94,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "7x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
        ],
        8: [
            {
                bracket: "8x84",
                minAverage: 78,
                maxAverage: 85,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "8x94",
                minAverage: 86,
                maxAverage: 94,
                status: "Deprecated!",
                exceptions: "",
                type: "",
            },
            {
                bracket: "8x100",
                minAverage: 95,
                maxAverage: 100.9,
                status: "Active!",
                exceptions: "",
                type: "",
            },
        ]
    }
}